services:
  api-gateway-dev:
    container_name: api-gateway-dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1000/api/v1/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 15s
    build:
      context: ../../
      dockerfile: deployment/docker/Dockerfile
      target: development
    ports:
      - "1000:1000"
    volumes:
      - ../../:/app
    networks:
      - moufube-dev

networks:
  moufube-dev:
    external: true

     