services:
  redis:
    container_name: redis-dev
    image: redis:8.4.0-alpine3.22
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    ports:
      - "6379:6379"
    networks:
      - moufube-dev
    volumes:
      - moufube-cache-dev:/data

  api-gateway-dev:
    container_name: api-gateway-dev
    build:
      context: ../../
      dockerfile: deployment/docker/Dockerfile
      target: development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1000/api/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 15s
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "1000:1000"
    volumes:
      - ../../:/app
    networks:
      - moufube-dev

networks:
  moufube-dev:
    external: true

volumes:
  moufube-cache-dev: