services:
  authentication-db-dev:
    container_name: authentication-db-dev
    image: postgres:16.11-alpine3.23
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p 5432 -U $POSTGRES_USER"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "2001:5432"
    volumes:
      - moufube-authentication-dev:/var/lib/postgresql/data
    networks:
      - moufube-dev

  authentication-service-dev:
    container_name: authentication-service-dev
    build:
      context: ../../
      dockerfile: deployment/docker/Dockerfile
      target: development
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:1001/api/health"]
    #   interval: 30s
    #   timeout: 3s
    #   retries: 3
    #   start_period: 15s
    depends_on:
      authentication-db-dev:
        condition: service_healthy
    ports:
      - "1000:1000"
    volumes:
      - ../../:/app
    networks:
      - moufube-dev

networks:
  moufube-dev:
    external: true

volumes:
  moufube-authentication-dev: